// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { VITE_SUPABASE_PUBLISHABLE_KEY } from "@/const";
import { VITE_SUPABASE_URL } from "@/const";


const SUPABASE_URL = VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});